### ISSUE TITLE
Optimize zap for DevGarden updates

### ISSUE THREAD

**Issue by windfee** [consiliera/babysteps#12]
Create a zap in Zapier that updates a news widget on developer.seedtoken.io

- create news widget in Webflow
- create zap trigger in Zapier (when new repo is created)
- create update of CMS item in Webflow

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/828640131766201/838089804157053)

**Comment by windfee** [comment]
optimise the zap

**Comment by kerigpc** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
Ricardomol, @Maksandre, @LeonKennedy, @chungquantin, @iakarsu, @debnath-d, @RamesesLabs, @craigwilliams84, @brendon-rofe, @Jmgmartig, @hqwangningbo, @kennethkoch, @Runskey, @0xJayShen, @carte7000, @vdnnf, @maciejry, @UltimoTG, @rjoshima, @sriganesh
