### ISSUE TITLE
test synchronization between github and asana by updating issues on both sides

### ISSUE THREAD

**Issue by windfee** [consiliera/babysteps#2]
the title says it all

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/828640131766201/828519368873744)

**Comment by windfee** [comment]
➤ Gaby@SEED commented:

hmmm - subtasks don't seem to appear on github (makes sense - where would github put them?)

**Comment by phildhall** [comment]
I'd expect them to be shown as part of the flow of the main task. Or it's a question for support to answer I would think. 

Maybe a sub task is separate but linked ...
