### ISSUE TITLE
This is a bug made in Baby Steps care of Mrs S

### ISSUE THREAD

**Issue by phildhall** [consiliera/babysteps#6]
So this is referencing #2 but where is the subtask indeed ?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/828640131766201/829861938652031)

**Comment by phildhall** [comment]
@consiliera - I can't add a label here, I've not got the permissions.

**Comment by windfee** [comment]
@phildhall that's right Mr H, you can't be God everywhere ;-) I'll give you permission of course

**Comment by windfee** [comment]
strangely enough, I can not. What the heck. I'll close this bug now for testing reasons.
